### ISSUE TITLE
add territory boundaries to Northern Canada 

### ISSUE THREAD

**Issue by e-schott** [e-schott/youngest-bilingual-canadians-2022#1]
![image](https://user-images.githubusercontent.com/8550869/148810018-32215e6d-0eb9-4f33-8cc9-09c16aa11d08.png)

**Comment by surchs** [comment]
@e-schott: Northern Canada is a combined region. There are also cities that are combined (e.g. Moncton - St. John.) and use a combined shape. How do you represent that the values across these regions are an average and they don't just happen to have the same value individually?

**Comment by surchs** [comment]
Should be closed with 34a3c08
