### ISSUE TITLE
update Language Pairs table

### ISSUE THREAD

**Issue by e-schott** [e-schott/youngest-bilingual-canadians-2022#15]
This has additional rows for provinces: 
https://github.com/e-schott/BilingalismCanada/blob/master/03_output/02_tables/Tables_language_pairs_for_dashboard.csv
none of the naming of the areas should have changes, so should be straightforward?

**Comment by surchs** [comment]
Can you replace the [`language_pairs.csv`](https://github.com/e-schott/youngest-bilingual-canadians-2022/blob/main/assets/language_pairs.csv) table in the assets folder with this one and then see if the app breaks. If it doesn't, then this should be all we need.

**Comment by surchs** [comment]
@e-schott: can you check that this has done what you expect? I don't notice any difference

**Comment by e-schott** [comment]
yes! thank you!
